import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.49.4";

type Workspace = "hr" | "growth" | "business";
type Provider = "gemini" | "groq" | "openrouter";
type ToolCall = { name:string; args:Record<string,unknown>; callId?:string };
type ProviderResult = { text:string; toolCalls:ToolCall[]; rawAssistant?:unknown; inputTokens?:number; outputTokens?:number; thoughtsTokens?:number; finishReason?:string };

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"";
const ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")??"";
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const admin=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const keyCache=new Map<string,string>();
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Cache-Control":"no-store"};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8"}})}
function text(v:unknown,max=1000){return typeof v==="string"?v.trim().slice(0,max):""}
function num(v:unknown,min:number,max:number,fallback:number){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}
function parseArgs(v:unknown){if(typeof v!=="string")return{};try{return JSON.parse(v) as Record<string,unknown>}catch{return{}}}
async function timedFetch(url:string,init:RequestInit,ms:number){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(t)}}
async function providerKey(name:"GEMINI_API_KEY"|"GROQ_API_KEY"|"OPENROUTER_API_KEY"){const c=keyCache.get(name);if(c)return c;const{data,error}=await admin.rpc("get_ai_provider_secret",{p_name:name});const vault=typeof data==="string"?data.trim():"";if(!error&&vault){keyCache.set(name,vault);return vault}const env=Deno.env.get(name)?.trim();if(env){keyCache.set(name,env);return env}return null}

function sanitize(v:unknown,depth=0):unknown{
 if(depth>7)return"[truncated]";
 if(Array.isArray(v))return v.slice(0,60).map(x=>sanitize(x,depth+1));
 if(!v||typeof v!=="object")return typeof v==="string"?v.slice(0,2000):v;
 const blocked=/(phone|email|address|national|nid|id_number|bank|iban|account_number|card_number|receipt|photo|image_path|verification|latitude|longitude|accuracy|device_token|password|secret|purchase_price|unit_cost|cost_price)/i;
 const out:Record<string,unknown>={};for(const[k,x]of Object.entries(v as Record<string,unknown>)){if(!blocked.test(k))out[k]=sanitize(x,depth+1)}return out;
}
function payrollSummary(raw:any){if(!raw||typeof raw!=="object")return sanitize(raw);const out:Record<string,unknown>={};for(const[k,v]of Object.entries(raw)){if(Array.isArray(v))out[`${k}_count`]=v.length;else if(v&&typeof v==="object")out[k]=sanitize(v);else out[k]=v}return sanitize(out)}

const workspacePrompts:Record<Workspace,string>={
 hr:`أنت Elmadawy HR AI، مساعد موارد بشرية داخلي للمعداوي ماركت. رد بالعربية المصرية المهنية المختصرة. استخدم الأدوات قبل أي رقم أو حالة تشغيلية. ركز على الحضور، الورديات، الإجازات، وتلخيص الرواتب دون كشف بيانات شخصية أو تفاصيل راتب فردية. لا تتخذ قرار توظيف أو فصل أو جزاء أو اعتماد إجازة أو تعديل راتب. أي إجراء يحتاج مراجعة بشرية وتأكيد صريح. لا تستنتج صفات شخصية أو صحية عن الموظفين.`,
 growth:`أنت Elmadawy Growth AI، مساعد النمو وتجربة العميل. رد بالعربية المصرية المهنية المختصرة. استخدم الأدوات قبل ذكر نتائج الحملات أو الصفحة الرئيسية أو البانرات أو التحويل. حلل CTR والتحويل والمحتوى والتجارب، لكن لا تنشر محتوى ولا ترسل حملة ولا تعدل عرضًا تلقائيًا. أي Action يحتاج تأكيد بشري. لا تعرض بيانات عميل شخصية.`,
 business:`أنت Elmadawy Business AI، مساعد إدارة الفروع والأداء. رد بالعربية المصرية المهنية المختصرة. استخدم التقارير الموثوقة قبل أي رقم. حلل المبيعات والربحية والمخزون والطلبات والورديات والتحويلات بين الفروع. لا تعدل مخزونًا أو سعرًا أو مالًا أو مشتريات تلقائيًا؛ اقترح إجراء فقط ويحتاج تأكيد بشري.`
};

const commonRange=(args:Record<string,unknown>)=>{const days=Math.round(num(args.days,1,90,7));const to=new Date();const from=new Date(to.getTime()-days*86400000);return{from:from.toISOString(),to:to.toISOString(),days}};
const businessSections=["overview","sales","profitability","inventory","products","shifts","online","insights","inventory_transfers"];

function toolsFor(workspace:Workspace){
 if(workspace==="hr")return[
  {name:"get_hr_attendance",description:"اقرأ لوحة الحضور ليوم محدد في الفرع.",parameters:{type:"object",properties:{date:{type:"string",description:"YYYY-MM-DD"}}}},
  {name:"get_hr_shift_schedule",description:"اقرأ جدول الورديات الحالي وتغطية الموظفين.",parameters:{type:"object",properties:{}}},
  {name:"get_hr_leave_calendar",description:"اقرأ تقويم الإجازات لفترة زمنية.",parameters:{type:"object",properties:{days:{type:"integer",description:"1-90 يوم"}}}},
  {name:"get_hr_payroll_summary",description:"اقرأ ملخص مسير الرواتب للشهر بدون كشف تفاصيل راتب فردي.",parameters:{type:"object",properties:{month:{type:"integer"},year:{type:"integer"}}}}
 ];
 if(workspace==="growth")return[
  {name:"get_growth_analytics",description:"اقرأ Analytics الموثوقة لأقسام الصفحة الرئيسية والتجارب.",parameters:{type:"object",properties:{days:{type:"integer",description:"1-365 يوم"}}}},
  {name:"get_growth_home_state",description:"اقرأ حالة الصفحة الرئيسية المنشورة والمسودة والأقسام بدون تعديل.",parameters:{type:"object",properties:{}}},
  {name:"get_growth_banners",description:"اقرأ البانرات وحالتها ومواعيدها بدون تعديل.",parameters:{type:"object",properties:{limit:{type:"integer"}}}},
  {name:"get_growth_notification_history",description:"اقرأ سجل حملات الإشعارات للفرع بدون إرسال أي حملة.",parameters:{type:"object",properties:{limit:{type:"integer"}}}}
 ];
 return[
  {name:"get_business_report",description:"اقرأ تقرير إدارة فرع موثوق من Reporting V2.",parameters:{type:"object",properties:{section:{type:"string",enum:businessSections},days:{type:"integer",description:"1-90 يوم"}},required:["section"]}},
  {name:"get_business_branch",description:"اقرأ بيانات الفرع الحالي.",parameters:{type:"object",properties:{}}}
 ];
}

function allowedWorkspace(perms:Set<string>,superAdmin:boolean,w:Workspace){if(superAdmin)return true;if(w==="hr")return[...perms].some(p=>p.startsWith("hr."));if(w==="growth")return["growth_console.access","home_content.view","home_content.manage","home_content.publish"].some(p=>perms.has(p));return["reports.view","inventory.manage","online_orders.view","pos.manage_shifts"].some(p=>perms.has(p))}

async function executeTool(client:any,workspace:Workspace,branchId:string,call:ToolCall,perms:Set<string>,superAdmin:boolean){const started=Date.now();const rpc=async(name:string,args:Record<string,unknown>)=>{const{data,error}=await client.rpc(name,args);if(error)throw new Error(error.message||"TOOL_FAILED");return data};try{let result:unknown;
 if(workspace==="hr"){
  if(call.name==="get_hr_attendance"){if(!superAdmin&&!perms.has("hr.attendance.view")&&!perms.has("hr.attendance.manage")&&!perms.has("hr.admin"))throw new Error("TOOL_PERMISSION_DENIED");const d=text(call.args.date,10)||new Date().toISOString().slice(0,10);result=sanitize(await rpc("get_hr_attendance_control_v1",{p_branch_id:branchId,p_date:d}))}
  else if(call.name==="get_hr_shift_schedule"){if(!superAdmin&&!perms.has("hr.shifts.view")&&!perms.has("hr.shifts.manage")&&!perms.has("hr.admin"))throw new Error("TOOL_PERMISSION_DENIED");result=sanitize(await rpc("get_hr_shift_scheduler_v1",{p_branch_id:branchId}))}
  else if(call.name==="get_hr_leave_calendar"){if(!superAdmin&&!perms.has("hr.leave.view")&&!perms.has("hr.leave.manage")&&!perms.has("hr.admin"))throw new Error("TOOL_PERMISSION_DENIED");const days=Math.round(num(call.args.days,1,90,30)),from=new Date(),to=new Date(from.getTime()+days*86400000);result=sanitize(await rpc("get_hr_leave_calendar_v1",{p_branch_id:branchId,p_from:from.toISOString().slice(0,10),p_to:to.toISOString().slice(0,10)}))}
  else if(call.name==="get_hr_payroll_summary"){if(!superAdmin&&!perms.has("hr.payroll.view")&&!perms.has("hr.payroll.manage")&&!perms.has("hr.admin"))throw new Error("TOOL_PERMISSION_DENIED");const now=new Date(),m=Math.round(num(call.args.month,1,12,now.getMonth()+1)),y=Math.round(num(call.args.year,2020,2100,now.getFullYear()));result=payrollSummary(await rpc("get_hr_payroll_workspace_v2",{p_branch_id:branchId,p_month:m,p_year:y}))}
  else throw new Error("TOOL_NOT_ALLOWED");
 } else if(workspace==="growth"){
  if(call.name==="get_growth_analytics"){if(!superAdmin&&!perms.has("growth_console.access")&&!perms.has("home_content.view")&&!perms.has("home_content.manage"))throw new Error("TOOL_PERMISSION_DENIED");result=sanitize(await rpc("get_home_section_analytics",{p_days:Math.round(num(call.args.days,1,365,30))}))}
  else if(call.name==="get_growth_home_state"){if(!superAdmin&&!perms.has("home_content.view")&&!perms.has("home_content.manage")&&!perms.has("home_content.publish"))throw new Error("TOOL_PERMISSION_DENIED");const{data:pages,error:e1}=await client.from("home_pages").select("id,name,status,version,is_default,published_at,updated_at").eq("is_default",true).order("version",{ascending:false}).limit(5);if(e1)throw e1;const ids=(pages||[]).map((x:any)=>x.id);const{data:sections,error:e2}=ids.length?await client.from("home_sections").select("id,home_page_id,section_key,section_type,title,sort_order,is_active,starts_at,ends_at,audience_segments,experiment_key,experiment_variant").in("home_page_id",ids).order("sort_order"):({data:[],error:null} as any);if(e2)throw e2;result=sanitize({pages,sections})}
  else if(call.name==="get_growth_banners"){if(!superAdmin&&!perms.has("growth_console.banners.manage")&&!perms.has("home_content.view"))throw new Error("TOOL_PERMISSION_DENIED");const{data,error}=await client.from("banners").select("id,title,active,position,start_date,end_date,category_id,company_id").order("position").limit(Math.round(num(call.args.limit,1,50,20)));if(error)throw error;result=sanitize(data)}
  else if(call.name==="get_growth_notification_history"){if(!superAdmin&&!perms.has("growth_console.access"))throw new Error("TOOL_PERMISSION_DENIED");result=sanitize(await rpc("get_notification_campaign_history_v3",{p_branch_id:branchId,p_limit:Math.round(num(call.args.limit,1,30,10)),p_offset:0}))}
  else throw new Error("TOOL_NOT_ALLOWED");
 } else {
  if(call.name==="get_business_branch"){const{data,error}=await client.from("branches").select("id,name,code,active").eq("id",branchId).maybeSingle();if(error)throw error;result=sanitize(data||{found:false})}
  else if(call.name==="get_business_report"){if(!superAdmin&&!perms.has("reports.view"))throw new Error("TOOL_PERMISSION_DENIED");const section=text(call.args.section,40);if(!businessSections.includes(section))throw new Error("INVALID_REPORT_SECTION");const r=commonRange(call.args),common={p_branch_id:branchId,p_from:r.from,p_to:r.to};const map:Record<string,[string,Record<string,unknown>]>={overview:["get_reporting_overview_v2",common],sales:["get_reporting_sales_v2",{...common,p_channel:"all",p_cashier_id:null,p_payment_code:null,p_search:null,p_limit:25,p_offset:0}],profitability:["get_reporting_profitability_v2",common],inventory:["get_reporting_inventory_v2",common],products:["get_reporting_products_v2",{...common,p_limit:25}],shifts:["get_reporting_shifts_v2",{...common,p_limit:25}],online:["get_reporting_online_v2",{...common,p_limit:25}],insights:["get_reporting_insights_v2",common],inventory_transfers:["get_reporting_inventory_transfers_v2",common]};const[name,args]=map[section];result=sanitize({section,range:r,report:await rpc(name,args)})}
  else throw new Error("TOOL_NOT_ALLOWED");
 }
 return{ok:true,result,duration_ms:Date.now()-started}}catch(e){return{ok:false,error:e instanceof Error?e.message:"TOOL_FAILED",duration_ms:Date.now()-started}}}

function geminiHistory(rows:any[]){return rows.map(r=>({role:r.role==="assistant"?"model":"user",parts:[{text:r.content}]}))}
function openHistory(rows:any[]){return rows.map(r=>({role:r.role,content:r.content}))}
async function callGemini(model:string,system:string,messages:any[],tools:any[],timeout:number,maxTokens:number):Promise<ProviderResult>{const key=await providerKey("GEMINI_API_KEY");if(!key)throw new Error("GEMINI_NOT_CONFIGURED");const res=await timedFetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:messages,tools:tools.length?[{functionDeclarations:tools}]:undefined,generationConfig:{maxOutputTokens:maxTokens,thinkingConfig:{thinkingLevel:"LOW"}}})},timeout);if(!res.ok)throw new Error(`GEMINI_${res.status}`);const p=await res.json(),c=p?.candidates?.[0]||{},parts=c?.content?.parts||[];return{text:parts.map((x:any)=>x.text||"").join("\n").trim(),toolCalls:parts.filter((x:any)=>x.functionCall).map((x:any)=>({name:x.functionCall.name,args:x.functionCall.args||{},callId:x.functionCall.id||undefined})),rawAssistant:c.content,inputTokens:p?.usageMetadata?.promptTokenCount,outputTokens:p?.usageMetadata?.candidatesTokenCount,thoughtsTokens:p?.usageMetadata?.thoughtsTokenCount,finishReason:c?.finishReason}}
async function callOpen(provider:"groq"|"openrouter",model:string,system:string,messages:any[],tools:any[],timeout:number,maxTokens:number):Promise<ProviderResult>{const key=await providerKey(provider==="groq"?"GROQ_API_KEY":"OPENROUTER_API_KEY");if(!key)throw new Error(`${provider.toUpperCase()}_NOT_CONFIGURED`);const url=provider==="groq"?"https://api.groq.com/openai/v1/chat/completions":"https://openrouter.ai/api/v1/chat/completions",headers:Record<string,string>={"Content-Type":"application/json",Authorization:`Bearer ${key}`};if(provider==="openrouter")headers["X-Title"]="Elmadawy AI Workspaces";const res=await timedFetch(url,{method:"POST",headers,body:JSON.stringify({model,messages:[{role:"system",content:system},...messages],tools:tools.length?tools.map(t=>({type:"function",function:t})):undefined,tool_choice:tools.length?"auto":undefined,temperature:0.1,max_tokens:maxTokens})},timeout);if(!res.ok)throw new Error(`${provider.toUpperCase()}_${res.status}`);const p=await res.json(),a=p?.choices?.[0]?.message||{};return{text:a.content||"",toolCalls:(a.tool_calls||[]).map((x:any)=>({name:x.function.name,args:parseArgs(x.function.arguments),callId:x.id})),rawAssistant:a,inputTokens:p?.usage?.prompt_tokens,outputTokens:p?.usage?.completion_tokens,finishReason:p?.choices?.[0]?.finish_reason}}
async function callProvider(provider:Provider,model:string,system:string,messages:any[],tools:any[],timeout:number,maxTokens:number){return provider==="gemini"?callGemini(model,system,messages,tools,timeout,maxTokens):callOpen(provider,model,system,messages,tools,timeout,maxTokens)}
function appendTools(provider:Provider,messages:any[],assistant:ProviderResult,calls:Array<{request:ToolCall;output:unknown}>){if(provider==="gemini"){messages.push(assistant.rawAssistant||{role:"model",parts:[]});messages.push({role:"user",parts:calls.map(({request,output})=>({functionResponse:{name:request.name,...(request.callId?{id:request.callId}:{}),response:output}}))})}else{messages.push(assistant.rawAssistant||{role:"assistant",content:assistant.text});for(const{request,output}of calls)messages.push({role:"tool",tool_call_id:request.callId||crypto.randomUUID(),content:JSON.stringify(output)})}}

const actionTypes:Record<Workspace,string[]>={hr:["attendance_anomaly_review","shift_coverage_review","leave_request_review","payroll_anomaly_review","employee_followup"],growth:["growth_content_review","growth_campaign_review","growth_offer_review"],business:["branch_performance_review","inventory_recount_review","low_stock_review","overdue_order_followup","shift_variance_review","expense_anomaly_review","supplier_reorder_review"]};
function actionPrompt(w:Workspace){return `أنت Action Planner آمن لمساحة ${w}. حول التحليل الموجود إلى اقتراح مراجعة بشرية واحد فقط عند وجود إجراء واضح. الأنواع المسموحة: ${actionTypes[w].join(", ")}. لا تنفذ أي تعديل. أرجع JSON فقط: {"should_propose":true,"action_type":"...","title":"...","description":"...","priority":"normal|high|urgent","reason":"..."} أو {"should_propose":false,"reason":"..."}.`}
function parseDecision(raw:string,w:Workspace){const s=raw.indexOf("{"),e=raw.lastIndexOf("}");if(s<0||e<s)throw new Error("ACTION_JSON_INVALID");const d=JSON.parse(raw.slice(s,e+1));if(d.should_propose!==true)return{should_propose:false,reason:text(d.reason,700)||"لا يوجد إجراء واضح."};if(!actionTypes[w].includes(d.action_type))throw new Error("ACTION_TYPE_INVALID");const title=text(d.title,200);if(title.length<3)throw new Error("ACTION_TITLE_INVALID");return{should_propose:true,action_type:d.action_type,title,description:text(d.description,1800),priority:["normal","high","urgent"].includes(d.priority)?d.priority:"normal",reason:text(d.reason,900)}}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return json({error:"سجل الدخول أولاً."},401);
 const client=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const{data:authData,error:authError}=await client.auth.getUser();if(authError||!authData.user)return json({error:"جلسة الدخول غير صالحة."},401);
 let body:any;try{body=await req.json()}catch{return json({error:"طلب غير صالح."},400)}
 const workspace=text(body.workspace,20) as Workspace,branchId=text(body.branch_id,80),mode=text(body.mode,30)||"chat";if(!["hr","growth","business"].includes(workspace)||!uuid.test(branchId))return json({error:"مساحة العمل أو الفرع غير صالح."},400);
 const[{data:identity,error:ie},{data:branches,error:be}]=await Promise.all([client.rpc("get_my_staff_identity"),client.rpc("get_my_staff_branches")]);const bc=Array.isArray(branches)?branches.find((x:any)=>x?.branch_id===branchId):null,perms=new Set<string>(Array.isArray(bc?.permissions)?bc.permissions:[]),superAdmin=identity?.user_id===authData.user.id&&identity?.is_super_admin===true;if(ie||be||identity?.user_id!==authData.user.id||!bc||!allowedWorkspace(perms,superAdmin,workspace))return json({error:"ليس لديك صلاحية استخدام AI في مساحة العمل دي لهذا الفرع."},403);
 const{data:settings}=await admin.from("ai_runtime_settings").select("*").eq("scope","global").single();if(!settings?.enabled)return json({error:"بوابة AI متوقفة حاليًا."},503);
 const providers=[{provider:settings.primary_provider as Provider,model:settings.primary_model as string},...(settings.fallback_provider&&settings.fallback_model?[{provider:settings.fallback_provider as Provider,model:settings.fallback_model as string}]:[]),...(settings.tertiary_provider&&settings.tertiary_model?[{provider:settings.tertiary_provider as Provider,model:settings.tertiary_model as string}]:[])].filter((x,i,a)=>a.findIndex(y=>y.provider===x.provider&&y.model===x.model)===i);
 if(mode==="propose_action"){
  const conversationId=text(body.conversation_id,80),messageId=text(body.message_id,80);if(!uuid.test(conversationId)||!uuid.test(messageId))return json({error:"اختار تحليل AI صالح."},400);const[{data:conv},{data:msg},{data:toolRows}]=await Promise.all([admin.from("ai_conversations").select("id,created_by,branch_id,channel").eq("id",conversationId).maybeSingle(),admin.from("ai_messages").select("id,conversation_id,role,content").eq("id",messageId).maybeSingle(),admin.from("ai_tool_calls").select("tool_name,result_summary,status").eq("conversation_id",conversationId).eq("status","success").order("created_at",{ascending:false}).limit(8)]);if(!conv||conv.created_by!==authData.user.id||conv.branch_id!==branchId||conv.channel!==`workspace_${workspace}`||!msg||msg.conversation_id!==conversationId||msg.role!=="assistant")return json({error:"التحليل غير متاح."},403);const prompt=`رد AI:\n${text(msg.content,6000)}\n\nأدلة الأدوات:\n${JSON.stringify(sanitize(toolRows||[])).slice(0,12000)}`;let decision:any=null,chosen:any=null,answer:ProviderResult|null=null;for(let i=0;i<providers.length&&!decision;i++){chosen=providers[i];try{answer=await callProvider(chosen.provider,chosen.model,actionPrompt(workspace),chosen.provider==="gemini"?[{role:"user",parts:[{text:prompt}]}]:[{role:"user",content:prompt}],[],Math.min(60000,Number(settings.timeout_ms||60000)),1200);decision=parseDecision(answer.text,workspace)}catch(e){await admin.from("ai_usage_logs").insert({conversation_id:conversationId,user_id:authData.user.id,branch_id:branchId,provider:chosen.provider,model:chosen.model,fallback_used:i>0,status:"error",error_code:text(e instanceof Error?e.message:"ACTION_FAILED",120),metadata:{channel:`workspace_${workspace}_action`,milestone:"multi_workspace_m4"}})}}if(!decision||!answer)return json({error:"تعذر تكوين اقتراح آمن."},503);if(!decision.should_propose)return json({proposal:null,reason:decision.reason,provider:chosen.provider,model:chosen.model});const{data:proposal,error:pe}=await client.rpc("create_ai_action_proposal_v1",{p_branch_id:branchId,p_conversation_id:conversationId,p_action_type:decision.action_type,p_title:decision.title,p_description:decision.description||null,p_priority:decision.priority,p_evidence:{reason:decision.reason,assistant_message_id:messageId,workspace},p_payload:{workspace},p_provider:chosen.provider,p_model:chosen.model});if(pe)return json({error:pe.message||"تعذر حفظ الاقتراح."},400);return json({proposal,reason:decision.reason,provider:chosen.provider,model:chosen.model});
 }
 const message=text(body.message,3000);if(!message)return json({error:"اكتب سؤالك أولاً."},400);const supplied=uuid.test(body.conversation_id||"")?body.conversation_id:null,conversationId=supplied||crypto.randomUUID();if(supplied){const{data:c}=await admin.from("ai_conversations").select("id,created_by,branch_id,channel").eq("id",supplied).maybeSingle();if(!c||c.created_by!==authData.user.id||c.branch_id!==branchId||c.channel!==`workspace_${workspace}`)return json({error:"المحادثة غير متاحة."},403)}else{await admin.from("ai_conversations").insert({id:conversationId,branch_id:branchId,created_by:authData.user.id,channel:`workspace_${workspace}`,assistant:`${workspace}_copilot`,status:"active"})}
 await admin.from("ai_messages").insert({conversation_id:conversationId,role:"user",content:message,created_by:authData.user.id});const{data:rows}=await admin.from("ai_messages").select("role,content").eq("conversation_id",conversationId).in("role",["user","assistant"]).order("created_at",{ascending:false}).limit(12);const history=(rows||[]).slice().reverse().map((r:any)=>({role:r.role,content:text(r.content,3000)})),decl=toolsFor(workspace),toolAudit:any[]=[];let final:ProviderResult|null=null,chosen:any=null,attempt=0;
 for(let i=0;i<providers.length&&!final;i++){chosen=providers[i];attempt=i+1;const messages=chosen.provider==="gemini"?geminiHistory(history):openHistory(history),started=Date.now();try{for(let round=0;round<5;round++){const ans=await callProvider(chosen.provider,chosen.model,workspacePrompts[workspace],messages,decl,Math.min(60000,Number(settings.timeout_ms||60000)),Math.min(8192,Number(settings.max_output_tokens||4096)));if(!ans.toolCalls.length){final=ans;break}const calls=[];for(const request of ans.toolCalls.slice(0,5)){const output=await executeTool(client,workspace,branchId,request,perms,superAdmin);toolAudit.push({name:request.name,status:output.ok?"success":"error",duration_ms:output.duration_ms});calls.push({request,output});await admin.from("ai_tool_calls").insert({conversation_id:conversationId,user_id:authData.user.id,branch_id:branchId,tool_name:request.name,risk_level:"read",arguments:request.args,result_summary:output.ok?output.result:{error:output.error},status:output.ok?"success":"error",duration_ms:output.duration_ms})}appendTools(chosen.provider,messages,ans,calls)}if(!final)throw new Error("TOOL_LOOP_LIMIT")}catch(e){await admin.from("ai_usage_logs").insert({conversation_id:conversationId,user_id:authData.user.id,branch_id:branchId,provider:chosen.provider,model:chosen.model,fallback_used:i>0,status:"error",latency_ms:Date.now()-started,error_code:text(e instanceof Error?e.message:"PROVIDER_FAILED",120),metadata:{channel:`workspace_${workspace}`,provider_attempt:attempt,milestone:"multi_workspace_m4"}})}}
 if(!final)return json({error:"مزودو AI غير متاحين حاليًا."},503);const reply=final.text||"لم أتمكن من تكوين إجابة واضحة.";const{data:saved}=await admin.from("ai_messages").insert({conversation_id:conversationId,role:"assistant",content:reply,created_by:authData.user.id,provider:chosen.provider,model:chosen.model}).select("id").single();await admin.from("ai_usage_logs").insert({conversation_id:conversationId,user_id:authData.user.id,branch_id:branchId,provider:chosen.provider,model:chosen.model,fallback_used:attempt>1,status:"success",input_tokens:final.inputTokens||null,output_tokens:final.outputTokens||null,metadata:{channel:`workspace_${workspace}`,provider_attempt:attempt,milestone:"multi_workspace_m4",thoughts_tokens:final.thoughtsTokens||null}});return json({conversation_id:conversationId,message_id:saved?.id,reply,provider:chosen.provider,model:chosen.model,fallback_used:attempt>1,tool_calls:toolAudit,workspace});
});