import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { startOfDay, startOfMonth, subDays } from "date-fns";
import { Banknote, Building2, CircleDollarSign, ReceiptText, RefreshCcw, ShieldAlert, UserRoundCheck } from "lucide-react";
import MainLayout from "@/components/layout/MainLayout";
import ReportsSectionNav from "@/components/reports/ReportsSectionNav";
import BrandLoader from "@/components/ui/BrandLoader";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { siteConfig } from "@/config/site";
import { fetchReportingCostsV2 } from "@/services/supabase/reportingCostsV2Service";
import { useBranchStore } from "@/stores/branchStore";

type PeriodPreset = "today" | "7d" | "30d" | "month" | "year";
const money = (value: number | null | undefined) => value == null ? "محجوب" : `${Number(value).toLocaleString("ar-EG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${siteConfig.currency}`;
const number = (value: number | null | undefined) => Number(value || 0).toLocaleString("ar-EG", { maximumFractionDigits: 2 });
const getRange = (preset: PeriodPreset) => { const now=new Date(); if(preset==="today")return{from:startOfDay(now),to:now,label:"اليوم"}; if(preset==="7d")return{from:startOfDay(subDays(now,6)),to:now,label:"آخر 7 أيام"}; if(preset==="month")return{from:startOfMonth(now),to:now,label:"هذا الشهر"}; if(preset==="year")return{from:new Date(now.getFullYear(),0,1),to:now,label:"هذه السنة"}; return{from:startOfDay(subDays(now,29)),to:now,label:"آخر 30 يوم"}; };
function Metric({title,value,hint,icon}:{title:string;value:string;hint:string;icon:React.ReactNode}){return <Card className="border-0 shadow-sm ring-1 ring-black/5"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-muted-foreground">{title}</p><p className="mt-2 text-2xl font-black">{value}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{hint}</p></div><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-primary/10 text-primary">{icon}</div></div></CardContent></Card>}

export default function ReportsCostsV2(){
  const {currentBranchId,currentBranchName}=useBranchStore(); const [period,setPeriod]=useState<PeriodPreset>("30d"); const range=useMemo(()=>getRange(period),[period]);
  const query=useQuery({queryKey:["reporting-costs-v2",currentBranchId,period],enabled:Boolean(currentBranchId),queryFn:()=>fetchReportingCostsV2(currentBranchId!,range.from,range.to,200),staleTime:30_000});
  if(!currentBranchId)return <MainLayout><div className="mx-auto mt-16 max-w-xl"><Alert><AlertDescription>اختر فرعًا أولًا لعرض تقرير المصروفات والموردين.</AlertDescription></Alert></div></MainLayout>;
  const summary=query.data?.summary; const canCosts=Boolean(query.data?.permissions.can_view_costs);
  return <MainLayout><div dir="rtl" className="mx-auto w-full max-w-[1600px] space-y-5 py-5"><ReportsSectionNav />
    <section className="rounded-3xl border bg-white p-5 shadow-sm md:p-7"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="mb-2 flex gap-2"><Badge variant="secondary">Costs V2</Badge><Badge variant="outline">{currentBranchName||"الفرع الحالي"}</Badge></div><h1 className="text-2xl font-black md:text-3xl">المصروفات والرواتب والموردون</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-muted-foreground">فصل واضح بين المصروف التشغيلي، الرواتب المدفوعة، ومشتريات المخزون. مستحقات المورد محسوبة من مشتريات الفرع فقط، ولا نستخدم الرصيد العالمي في Supplier Master.</p></div><div className="flex gap-2"><Select value={period} onValueChange={(v)=>setPeriod(v as PeriodPreset)}><SelectTrigger className="min-w-[170px] rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="today">اليوم</SelectItem><SelectItem value="7d">آخر 7 أيام</SelectItem><SelectItem value="30d">آخر 30 يوم</SelectItem><SelectItem value="month">هذا الشهر</SelectItem><SelectItem value="year">هذه السنة</SelectItem></SelectContent></Select><Button variant="outline" className="rounded-xl" onClick={()=>query.refetch()} disabled={query.isFetching}><RefreshCcw className={`ml-2 h-4 w-4 ${query.isFetching?"animate-spin":""}`}/>تحديث</Button></div></div></section>
    {query.isLoading?<div className="flex min-h-[420px] items-center justify-center"><BrandLoader size="lg"/></div>:query.isError||!summary?<Alert variant="destructive"><AlertDescription>تعذر تحميل تقرير المصروفات والموردين.</AlertDescription></Alert>:<>
      {!canCosts&&<Alert className="border-amber-200 bg-amber-50"><ShieldAlert className="h-4 w-4"/><AlertDescription>لديك صلاحية مشاهدة التقارير، لكن قيم التكلفة والرواتب مخفية لأن `reports.profit` غير متاحة لهذا الحساب.</AlertDescription></Alert>}
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Metric title="مصروفات تشغيلية" value={money(summary.active_expense_amount)} hint={`${number(summary.active_expense_records)} حركة فعالة`} icon={<ReceiptText className="h-5 w-5"/>}/><Metric title="رواتب مدفوعة" value={money(summary.salary_paid_amount)} hint={`${number(summary.salary_paid_records)} دفعة داخل ${range.label}`} icon={<UserRoundCheck className="h-5 w-5"/>}/><Metric title="مشتريات مخزون" value={money(summary.purchase_total)} hint={`${number(summary.purchase_count)} فاتورة شراء`} icon={<Building2 className="h-5 w-5"/>}/><Metric title="مدفوع للموردين" value={money(summary.purchase_paid_total)} hint={`مستحق نشأ بالفترة ${money(summary.purchase_outstanding_created)}`} icon={<Banknote className="h-5 w-5"/>}/><Metric title="إجمالي خروج تشغيلي" value={money(summary.operating_cash_out_in_period)} hint="مصروف فعال + راتب مدفوع + مدفوع مشتريات" icon={<CircleDollarSign className="h-5 w-5"/>}/><Metric title="مستحقات موردين حالية" value={money(summary.lifetime_supplier_outstanding)} hint={`${number(summary.suppliers_with_branch_history)} مورد له تاريخ شراء بالفرع`} icon={<Building2 className="h-5 w-5"/>}/></section>
      <Alert><AlertDescription>Supplier Master نفسه غير مربوط بالفرع، لذلك `suppliers.balance` غير مستخدم نهائيًا هنا. الرصيد المعروض = مجموع `purchases.total - paid` الخاصة بهذا الفرع فقط.</AlertDescription></Alert>
      <section className="grid gap-5 xl:grid-cols-2"><Card className="border-0 shadow-sm ring-1 ring-black/5"><CardHeader><CardTitle>المصروفات حسب النوع</CardTitle></CardHeader><CardContent className="space-y-2">{query.data!.expense_types.length===0?<p className="py-8 text-center text-sm text-muted-foreground">لا توجد مصروفات فعالة في الفترة.</p>:query.data!.expense_types.map(r=><div key={r.type} className="flex items-center justify-between rounded-2xl border p-4"><div><strong>{r.type}</strong><p className="text-xs text-muted-foreground">{number(r.records)} حركة</p></div><strong>{money(r.amount)}</strong></div>)}</CardContent></Card><Card className="border-0 shadow-sm ring-1 ring-black/5"><CardHeader><CardTitle>الموردون المرتبطون بالفرع</CardTitle></CardHeader><CardContent className="space-y-2">{query.data!.suppliers.length===0?<p className="py-8 text-center text-sm text-muted-foreground">لا يوجد تاريخ مشتريات موردين مسجل لهذا الفرع حتى الآن.</p>:query.data!.suppliers.map(r=><div key={r.supplier_id} className="rounded-2xl border p-4"><div className="flex items-center justify-between"><div><strong>{r.supplier_name}</strong><p className="text-xs text-muted-foreground">{r.phone||"بدون هاتف"}</p></div><strong>{money(r.lifetime_outstanding)}</strong></div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>{number(r.lifetime_purchase_count)} فاتورة تاريخيًا</span><span>مشتريات الفترة {money(r.period_purchase_total)}</span></div></div>)}</CardContent></Card></section>
      <section className="grid gap-5 xl:grid-cols-3"><Card className="border-0 shadow-sm ring-1 ring-black/5"><CardHeader><CardTitle>آخر المصروفات</CardTitle></CardHeader><CardContent className="space-y-2">{query.data!.expenses.length===0?<p className="py-8 text-center text-sm text-muted-foreground">لا يوجد.</p>:query.data!.expenses.map(r=><div key={r.expense_id} className="rounded-xl bg-muted/50 p-3"><div className="flex justify-between"><strong>{r.type||"غير مصنف"}</strong><span>{money(r.amount)}</span></div><p className="mt-1 text-xs text-muted-foreground">{new Date(r.date).toLocaleDateString("ar-EG")} • {r.status}</p></div>)}</CardContent></Card><Card className="border-0 shadow-sm ring-1 ring-black/5"><CardHeader><CardTitle>مشتريات الموردين</CardTitle></CardHeader><CardContent className="space-y-2">{query.data!.purchases.length===0?<p className="py-8 text-center text-sm text-muted-foreground">لا توجد مشتريات في الفترة.</p>:query.data!.purchases.map(r=><div key={r.purchase_id} className="rounded-xl bg-muted/50 p-3"><div className="flex justify-between"><strong>{r.supplier_name}</strong><span>{money(r.total)}</span></div><p className="mt-1 text-xs text-muted-foreground">مدفوع {money(r.paid)} • باقي {money(r.outstanding)}</p></div>)}</CardContent></Card><Card className="border-0 shadow-sm ring-1 ring-black/5"><CardHeader><CardTitle>الرواتب</CardTitle></CardHeader><CardContent className="space-y-2">{query.data!.salaries.length===0?<p className="py-8 text-center text-sm text-muted-foreground">لا توجد دفعات رواتب في الفترة.</p>:query.data!.salaries.map(r=><div key={r.salary_id} className="rounded-xl bg-muted/50 p-3"><div className="flex justify-between"><strong>{r.employee_name}</strong><span>{money(r.amount)}</span></div><p className="mt-1 text-xs text-muted-foreground">{r.month}/{r.year} • {r.status} {r.payment_date?`• ${new Date(`${r.payment_date}T12:00:00`).toLocaleDateString("ar-EG")}`:""}</p></div>)}</CardContent></Card></section>
    </>}
  </div></MainLayout>;
}
