import { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpLeft, Banknote, Building2, CreditCard, Landmark, RefreshCcw, WalletCards } from 'lucide-react';
import { money } from '../components/MetricCard';
import { fetchCashFlow, fetchFinanceAccounts, ReportingEngineUnavailableError, type CashFlowItem, type FinanceAccount } from '../services/businessFinance';
const iconMap = { cash: Banknote, bank: Landmark, card: CreditCard, wallet: WalletCards, other: Building2 };
export default function Finance() {
  const [accounts,setAccounts]=useState<FinanceAccount[]>([]); const [cashflow,setCashflow]=useState<CashFlowItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  async function load(){setLoading(true);setError(null);try{const [a,c]=await Promise.all([fetchFinanceAccounts({period:'today'}),fetchCashFlow({period:'today'})]);setAccounts(a);setCashflow(c);}catch(err){setAccounts([]);setCashflow([]);setError(err instanceof ReportingEngineUnavailableError?'Financial Engine الجديد لم يتم نشر RPCs الخاصة به بعد.':err instanceof Error?err.message:'تعذر تحميل البيانات المالية.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const incoming=cashflow.filter(i=>i.direction==='in').reduce((s,i)=>s+i.amount,0); const outgoing=cashflow.filter(i=>i.direction==='out').reduce((s,i)=>s+Math.abs(i.amount),0);
  return <div className="stack-lg"><section className="page-intro"><span className="eyebrow">Finance Workspace</span><h2>أين توجد أموال الشركة الآن؟</h2><p>الحسابات، المحافظ، التدفقات والتسويات من دفتر مالي واحد قابل للمراجعة.</p></section>{error&&<section className="engine-banner"><div><strong>الواجهة جاهزة للربط</strong><p>{error}</p></div><button className="secondary-button" onClick={()=>void load()}><RefreshCcw size={17}/> إعادة المحاولة</button></section>}
  <section className="account-grid">{accounts.length?accounts.map(account=>{const Icon=iconMap[account.kind]??Building2;return <article className="account-card" key={account.id}><div className="account-card__icon"><Icon size={22}/></div><span>{account.name}</span><strong>{money(account.balance)}</strong>{account.pending!=null&&account.pending!==0&&<small>معلق: {money(account.pending)}</small>}</article>;}):[1,2,3,4].map(i=><article className="account-card account-card--empty" key={i}><div className="skeleton small"/><div className="skeleton medium"/><div className="skeleton wide"/></article>)}</section>
  <section className="split-grid"><article className="section-card"><div className="section-heading"><div><span className="eyebrow">Cash Flow</span><h3>تدفق اليوم</h3></div></div><div className="flow-summary"><div className="flow-chip flow-chip--in"><ArrowUpLeft size={18}/><div><span>داخل</span><strong>{loading?'…':money(incoming)}</strong></div></div><div className="flow-chip flow-chip--out"><ArrowDownRight size={18}/><div><span>خارج</span><strong>{loading?'…':money(outgoing)}</strong></div></div></div><div className="net-flow"><span>صافي التدفق</span><strong>{loading?'…':money(incoming-outgoing)}</strong></div></article><article className="section-card"><div className="section-heading"><div><span className="eyebrow">Profit Waterfall</span><h3>تكوين صافي الربح</h3></div></div><div className="waterfall-placeholder"><span>Revenue</span><i>→</i><span>Net Sales</span><i>→</i><span>COGS</span><i>→</i><span>Gross Profit</span><i>→</i><span>Net Profit</span></div><p className="muted">القيم ستأتي من Invoice Snapshots والـLedgers فقط.</p></article></section>
  <section className="section-card"><div className="section-heading"><div><span className="eyebrow">آخر الحركات</span><h3>التدفقات المالية</h3></div></div><div className="rows-list">{cashflow.length?cashflow.slice(0,12).map(item=><div className="data-row data-row--two-line" key={item.id}><div><span>{item.label}</span><small>{new Date(item.occurredAt).toLocaleString('ar-EG')}</small></div><strong className={item.direction==='in'?'positive-text':'negative-text'}>{item.direction==='in'?'+':'−'} {money(Math.abs(item.amount))}</strong></div>):<div className="empty-data"><span>—</span><p>لا توجد حركات مالية متاحة من المحرك الجديد حتى الآن.</p></div>}</div></section></div>;
}
