create table if not exists public.order_operations_realtime_signals_v1 (
  id bigint generated by default as identity primary key,
  branch_id uuid not null references public.branches(id) on delete cascade,
  order_id uuid not null references public.online_orders(id) on delete cascade,
  event_type text not null,
  created_at timestamptz not null default now()
);

alter table public.order_operations_realtime_signals_v1 enable row level security;
revoke all on public.order_operations_realtime_signals_v1 from public,anon;
grant select on public.order_operations_realtime_signals_v1 to authenticated;

drop policy if exists order_operations_signal_select_v1 on public.order_operations_realtime_signals_v1;
create policy order_operations_signal_select_v1 on public.order_operations_realtime_signals_v1
for select to authenticated
using (
  private.staff_is_super_admin(auth.uid())
  or public.staff_has_permission('online_orders.view',branch_id)
  or public.staff_has_permission('online_orders.manage',branch_id)
  or public.staff_has_permission('online_orders.prepare',branch_id)
  or public.staff_has_permission('online_orders.intake',branch_id)
  or public.staff_has_permission('delivery.manage',branch_id)
);

create index if not exists order_operations_signal_branch_created_idx
on public.order_operations_realtime_signals_v1(branch_id,created_at desc);

create or replace function private.emit_order_operations_signal_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_branch uuid;
  v_order uuid;
  v_event text;
begin
  if tg_table_name='online_orders' then
    v_branch:=coalesce(new.branch_id,old.branch_id);
    v_order:=coalesce(new.id,old.id);
    if tg_op='INSERT' then v_event:='order_created';
    elsif new.status is distinct from old.status then v_event:='order_status_changed';
    else v_event:='order_updated'; end if;
  elsif tg_table_name='order_fulfillment_state_v1' then
    v_branch:=coalesce(new.branch_id,old.branch_id);
    v_order:=coalesce(new.order_id,old.order_id);
    v_event:='fulfillment_updated';
  else
    v_branch:=coalesce(new.branch_id,old.branch_id);
    v_order:=coalesce(new.order_id,old.order_id);
    v_event:='delivery_updated';
  end if;

  if v_branch is not null and v_order is not null then
    insert into public.order_operations_realtime_signals_v1(branch_id,order_id,event_type)
    values(v_branch,v_order,v_event);
  end if;
  return coalesce(new,old);
end;
$function$;

revoke all on function private.emit_order_operations_signal_v1() from public,anon,authenticated;

drop trigger if exists emit_order_operations_signal_from_order_v1 on public.online_orders;
create trigger emit_order_operations_signal_from_order_v1
after insert or update on public.online_orders
for each row execute function private.emit_order_operations_signal_v1();

drop trigger if exists emit_order_operations_signal_from_fulfillment_v1 on private.order_fulfillment_state_v1;
create trigger emit_order_operations_signal_from_fulfillment_v1
after insert or update on private.order_fulfillment_state_v1
for each row execute function private.emit_order_operations_signal_v1();

drop trigger if exists emit_order_operations_signal_from_delivery_v1 on private.delivery_order_assignments_v1;
create trigger emit_order_operations_signal_from_delivery_v1
after insert or update on private.delivery_order_assignments_v1
for each row execute function private.emit_order_operations_signal_v1();

do $publication$
begin
  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='order_operations_realtime_signals_v1'
  ) then
    alter publication supabase_realtime add table public.order_operations_realtime_signals_v1;
  end if;
end
$publication$;
