create table if not exists private.branch_channel_controls_v1 (
  branch_id uuid not null references public.branches(id) on delete cascade,
  channel text not null check (channel in ('pos','online_sales','customer_app','marketplace','delivery','pickup')),
  configured_enabled boolean not null default false,
  reason text,
  message_ar text,
  source text not null default 'manual' check (source in ('legacy_seed','manual','group_action','policy')),
  revision bigint not null default 1 check (revision > 0),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (branch_id, channel)
);

create index if not exists idx_branch_channel_controls_channel_v1
  on private.branch_channel_controls_v1(channel, configured_enabled, branch_id);

alter table private.branch_channel_controls_v1 enable row level security;
revoke all on private.branch_channel_controls_v1 from public, anon, authenticated;
grant select on private.branch_channel_controls_v1 to service_role;

create table if not exists private.branch_groups_v1 (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  merchant_id uuid references public.merchants(id) on delete cascade,
  code text not null,
  name text not null,
  group_type text not null default 'custom' check (group_type in ('region','operations','franchise_network','marketplace_network','custom')),
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, code),
  check (btrim(code) <> ''),
  check (btrim(name) <> '')
);

create index if not exists idx_branch_groups_tenant_v1
  on private.branch_groups_v1(tenant_id, active, group_type);
create index if not exists idx_branch_groups_merchant_v1
  on private.branch_groups_v1(merchant_id) where merchant_id is not null;

alter table private.branch_groups_v1 enable row level security;
revoke all on private.branch_groups_v1 from public, anon, authenticated;
grant select on private.branch_groups_v1 to service_role;

create table if not exists private.branch_group_members_v1 (
  group_id uuid not null references private.branch_groups_v1(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (group_id, branch_id)
);

create index if not exists idx_branch_group_members_branch_v1
  on private.branch_group_members_v1(branch_id, group_id);

alter table private.branch_group_members_v1 enable row level security;
revoke all on private.branch_group_members_v1 from public, anon, authenticated;
grant select on private.branch_group_members_v1 to service_role;

create table if not exists private.business_structure_audit_v1 (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  entity_type text not null check (entity_type in ('branch_channel','branch_group','branch_group_members')),
  entity_id uuid,
  branch_id uuid references public.branches(id) on delete set null,
  action text not null,
  before_state jsonb,
  after_state jsonb,
  reason text,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_business_structure_audit_tenant_v1
  on private.business_structure_audit_v1(tenant_id, created_at desc);
create index if not exists idx_business_structure_audit_branch_v1
  on private.business_structure_audit_v1(branch_id, created_at desc) where branch_id is not null;

alter table private.business_structure_audit_v1 enable row level security;
revoke all on private.business_structure_audit_v1 from public, anon, authenticated;
grant select on private.business_structure_audit_v1 to service_role;

insert into private.branch_channel_controls_v1(branch_id, channel, configured_enabled, source)
select b.id, c.channel,
  case c.channel
    when 'pos' then coalesce(b.active,false)
    when 'online_sales' then coalesce(b.active,false) and m.merchant_type='owned'
    when 'customer_app' then coalesce(b.active,false) and m.merchant_type='owned'
    when 'marketplace' then coalesce(b.marketplace_customer_enabled,false)
    when 'delivery' then coalesce(b.delivery_enabled,false)
    when 'pickup' then false
    else false
  end,
  'legacy_seed'
from public.branches b
join public.merchants m on m.id=b.merchant_id
cross join (values ('pos'::text),('online_sales'),('customer_app'),('marketplace'),('delivery'),('pickup')) c(channel)
on conflict (branch_id,channel) do nothing;

create or replace function public.can_manage_business_structure_v1(p_tenant_id uuid)
returns boolean
language sql
stable
security definer
set search_path=''
as $$
  select public.is_super_admin()
    or exists (
      select 1
      from public.tenant_users tu
      where tu.tenant_id=p_tenant_id
        and tu.user_id=auth.uid()
        and tu.role in ('owner','admin')
        and coalesce(tu.is_active,true)
    );
$$;

revoke all on function public.can_manage_business_structure_v1(uuid) from public, anon;
grant execute on function public.can_manage_business_structure_v1(uuid) to authenticated, service_role;

create or replace function private.branch_channel_runtime_v1(p_branch_id uuid, p_channel text)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_branch public.branches%rowtype;
  v_merchant public.merchants%rowtype;
  v_control private.branch_channel_controls_v1%rowtype;
  v_configured boolean;
  v_effective boolean := true;
  v_blocked jsonb := '[]'::jsonb;
  v_platform boolean;
begin
  if p_channel not in ('pos','online_sales','customer_app','marketplace','delivery','pickup') then
    raise exception using errcode='22023', message='INVALID_BRANCH_CHANNEL';
  end if;

  select * into v_branch from public.branches where id=p_branch_id;
  if v_branch.id is null then
    raise exception using errcode='P0002', message='BRANCH_NOT_FOUND';
  end if;
  select * into v_merchant from public.merchants where id=v_branch.merchant_id;
  if v_merchant.id is null then
    raise exception using errcode='P0002', message='BRANCH_MERCHANT_NOT_FOUND';
  end if;

  select * into v_control
  from private.branch_channel_controls_v1
  where branch_id=p_branch_id and channel=p_channel;

  v_configured := coalesce(v_control.configured_enabled,
    case p_channel
      when 'pos' then coalesce(v_branch.active,false)
      when 'online_sales' then coalesce(v_branch.active,false) and v_merchant.merchant_type='owned'
      when 'customer_app' then coalesce(v_branch.active,false) and v_merchant.merchant_type='owned'
      when 'marketplace' then coalesce(v_branch.marketplace_customer_enabled,false)
      when 'delivery' then coalesce(v_branch.delivery_enabled,false)
      when 'pickup' then false
      else false
    end
  );

  if not v_configured then
    v_effective:=false;
    v_blocked:=v_blocked || jsonb_build_array('branch_channel_disabled');
  end if;
  if not coalesce(v_branch.active,false) then
    v_effective:=false;
    v_blocked:=v_blocked || jsonb_build_array('branch_inactive');
  end if;
  if v_merchant.status <> 'active' then
    v_effective:=false;
    v_blocked:=v_blocked || jsonb_build_array('merchant_inactive');
  end if;

  if p_channel='pos' then
    v_platform:=private.tenant_capability_enabled_v1(v_branch.tenant_id,'pos');
    if not v_platform then v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('tenant_pos_disabled'); end if;
  elsif p_channel='online_sales' then
    v_platform:=private.tenant_capability_enabled_v1(v_branch.tenant_id,'online_sales');
    if not v_platform then v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('tenant_online_sales_disabled'); end if;
    v_platform:=private.tenant_capability_enabled_v1(v_branch.tenant_id,'customer_app');
    if not v_platform then v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('tenant_customer_app_disabled'); end if;
  elsif p_channel='customer_app' then
    v_platform:=private.tenant_capability_enabled_v1(v_branch.tenant_id,'customer_app');
    if not v_platform then v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('tenant_customer_app_disabled'); end if;
  elsif p_channel='marketplace' then
    v_platform:=private.tenant_capability_enabled_v1(v_branch.tenant_id,'online_sales');
    if not v_platform then v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('tenant_online_sales_disabled'); end if;
    v_platform:=private.tenant_capability_enabled_v1(v_branch.tenant_id,'customer_app');
    if not v_platform then v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('tenant_customer_app_disabled'); end if;
    if v_merchant.merchant_type not in ('partner','franchise') then
      v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('merchant_not_marketplace');
    end if;
    if v_merchant.customer_published_at is null then
      v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('merchant_not_published');
    end if;
    if not coalesce(v_branch.marketplace_customer_enabled,false) then
      v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('branch_not_marketplace_published');
    end if;
  elsif p_channel='delivery' then
    v_platform:=private.tenant_capability_enabled_v1(v_branch.tenant_id,'delivery');
    if not v_platform then v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('tenant_delivery_disabled'); end if;
    if not coalesce(v_branch.delivery_enabled,false) then
      v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('legacy_delivery_disabled');
    end if;
  elsif p_channel='pickup' then
    v_platform:=private.tenant_capability_enabled_v1(v_branch.tenant_id,'online_sales');
    if not v_platform then v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('tenant_online_sales_disabled'); end if;
    v_platform:=private.tenant_capability_enabled_v1(v_branch.tenant_id,'customer_app');
    if not v_platform then v_effective:=false; v_blocked:=v_blocked||jsonb_build_array('tenant_customer_app_disabled'); end if;
  end if;

  return jsonb_build_object(
    'branch_id',v_branch.id,
    'tenant_id',v_branch.tenant_id,
    'merchant_id',v_branch.merchant_id,
    'merchant_type',v_merchant.merchant_type,
    'channel',p_channel,
    'configured_enabled',v_configured,
    'effective_enabled',v_effective,
    'blocked_by',v_blocked,
    'reason',v_control.reason,
    'message_ar',v_control.message_ar,
    'source',coalesce(v_control.source,'legacy_fallback'),
    'revision',coalesce(v_control.revision,0),
    'updated_at',v_control.updated_at
  );
end;
$$;

revoke all on function private.branch_channel_runtime_v1(uuid,text) from public, anon, authenticated;
grant execute on function private.branch_channel_runtime_v1(uuid,text) to service_role;

create or replace function private.branch_channel_effective_enabled_v1(p_branch_id uuid,p_channel text)
returns boolean
language sql
stable
security definer
set search_path=''
as $$
  select coalesce((private.branch_channel_runtime_v1(p_branch_id,p_channel)->>'effective_enabled')::boolean,false);
$$;

revoke all on function private.branch_channel_effective_enabled_v1(uuid,text) from public, anon, authenticated;
grant execute on function private.branch_channel_effective_enabled_v1(uuid,text) to service_role;

create or replace function public.get_business_structure_v1(p_tenant_id uuid default null)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_tenant_id uuid:=p_tenant_id;
  v_tenant jsonb;
  v_summary jsonb;
  v_merchants jsonb;
  v_groups jsonb;
begin
  if v_tenant_id is null then
    if public.is_super_admin() then
      select t.id into v_tenant_id
      from public.tenants t
      order by case when coalesce((t.settings->>'is_platform_tenant')::boolean,false) then 0 else 1 end, t.created_at
      limit 1;
    else
      select tu.tenant_id into v_tenant_id
      from public.tenant_users tu
      where tu.user_id=auth.uid() and coalesce(tu.is_active,true)
      order by tu.created_at
      limit 1;
    end if;
  end if;

  if v_tenant_id is null or not public.has_tenant_access(v_tenant_id) then
    raise exception using errcode='42501',message='TENANT_ACCESS_REQUIRED';
  end if;

  select jsonb_build_object(
    'id',t.id,'name',t.name,'subdomain',t.subdomain,'status',t.status,
    'logo_url',t.logo_url,'country',t.country,'city',t.city
  ) into v_tenant
  from public.tenants t where t.id=v_tenant_id;

  select jsonb_build_object(
    'merchant_count',count(distinct m.id),
    'branch_count',count(b.id),
    'owned_branch_count',count(b.id) filter(where m.merchant_type='owned'),
    'franchise_branch_count',count(b.id) filter(where m.merchant_type='franchise'),
    'marketplace_branch_count',count(b.id) filter(where m.merchant_type='partner'),
    'active_branch_count',count(b.id) filter(where coalesce(b.active,false)),
    'online_branch_count',count(b.id) filter(where private.branch_channel_effective_enabled_v1(b.id,'online_sales')),
    'delivery_branch_count',count(b.id) filter(where private.branch_channel_effective_enabled_v1(b.id,'delivery'))
  ) into v_summary
  from public.merchants m
  left join public.branches b on b.merchant_id=m.id
  where m.tenant_id=v_tenant_id;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'id',m.id,'code',m.code,'name',m.name,'merchant_type',m.merchant_type,'status',m.status,
      'contact_name',m.contact_name,'phone',m.phone,'email',m.email,
      'customer_published_at',m.customer_published_at,
      'branch_count',(select count(*) from public.branches bx where bx.merchant_id=m.id),
      'branches',coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'id',b.id,'name',b.name,'code',b.code,'address',b.address,'active',b.active,
            'category',b.category::text,'branch_type',b.branch_type::text,
            'delivery_enabled',b.delivery_enabled,'marketplace_customer_enabled',b.marketplace_customer_enabled,
            'opens_at',b.opens_at,'closes_at',b.closes_at,
            'latitude',b.latitude,'longitude',b.longitude,
            'channels',(select jsonb_object_agg(c.channel,private.branch_channel_runtime_v1(b.id,c.channel))
                        from (values ('pos'::text),('online_sales'),('customer_app'),('marketplace'),('delivery'),('pickup')) c(channel)),
            'groups',coalesce((select jsonb_agg(jsonb_build_object('id',g.id,'code',g.code,'name',g.name,'group_type',g.group_type) order by g.name)
                               from private.branch_group_members_v1 gm join private.branch_groups_v1 g on g.id=gm.group_id
                               where gm.branch_id=b.id and g.active),'[]'::jsonb)
          ) order by b.name
        ) from public.branches b where b.merchant_id=m.id
      ),'[]'::jsonb)
    ) order by case m.merchant_type when 'owned' then 0 when 'franchise' then 1 else 2 end,m.name
  ),'[]'::jsonb) into v_merchants
  from public.merchants m
  where m.tenant_id=v_tenant_id;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'id',g.id,'code',g.code,'name',g.name,'group_type',g.group_type,'active',g.active,
      'merchant_id',g.merchant_id,'metadata',g.metadata,
      'branch_ids',coalesce((select jsonb_agg(gm.branch_id order by gm.branch_id) from private.branch_group_members_v1 gm where gm.group_id=g.id),'[]'::jsonb)
    ) order by g.name
  ),'[]'::jsonb) into v_groups
  from private.branch_groups_v1 g where g.tenant_id=v_tenant_id;

  return jsonb_build_object(
    'tenant',v_tenant,
    'summary',coalesce(v_summary,'{}'::jsonb),
    'merchants',v_merchants,
    'groups',v_groups,
    'generated_at',now()
  );
end;
$$;

revoke all on function public.get_business_structure_v1(uuid) from public, anon;
grant execute on function public.get_business_structure_v1(uuid) to authenticated, service_role;

create or replace function public.get_branch_control_detail_v1(p_branch_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_tenant_id uuid;
  v_result jsonb;
begin
  select b.tenant_id into v_tenant_id from public.branches b where b.id=p_branch_id;
  if v_tenant_id is null then raise exception using errcode='P0002',message='BRANCH_NOT_FOUND'; end if;
  if not public.has_tenant_access(v_tenant_id) then raise exception using errcode='42501',message='TENANT_ACCESS_REQUIRED'; end if;

  select jsonb_build_object(
    'branch',jsonb_build_object(
      'id',b.id,'tenant_id',b.tenant_id,'merchant_id',b.merchant_id,'name',b.name,'code',b.code,
      'address',b.address,'phone',b.phone,'email',b.email,'active',b.active,
      'category',b.category::text,'branch_type',b.branch_type::text,
      'independent_pricing',b.independent_pricing,'independent_inventory',b.independent_inventory,
      'inventory_source_branch_id',b.inventory_source_branch_id,'pricing_source_branch_id',b.pricing_source_branch_id,
      'delivery_enabled',b.delivery_enabled,'delivery_radius_km',b.delivery_radius_km,'delivery_fee',b.delivery_fee,
      'min_order_amount',b.min_order_amount,'estimated_delivery_minutes',b.estimated_delivery_minutes,
      'marketplace_customer_enabled',b.marketplace_customer_enabled,'opens_at',b.opens_at,'closes_at',b.closes_at,
      'latitude',b.latitude,'longitude',b.longitude
    ),
    'merchant',jsonb_build_object(
      'id',m.id,'code',m.code,'name',m.name,'merchant_type',m.merchant_type,'status',m.status,
      'contact_name',m.contact_name,'phone',m.phone,'email',m.email,'customer_published_at',m.customer_published_at
    ),
    'channels',(select jsonb_object_agg(c.channel,private.branch_channel_runtime_v1(b.id,c.channel))
                from (values ('pos'::text),('online_sales'),('customer_app'),('marketplace'),('delivery'),('pickup')) c(channel)),
    'groups',coalesce((select jsonb_agg(jsonb_build_object('id',g.id,'code',g.code,'name',g.name,'group_type',g.group_type) order by g.name)
                       from private.branch_group_members_v1 gm join private.branch_groups_v1 g on g.id=gm.group_id
                       where gm.branch_id=b.id and g.active),'[]'::jsonb),
    'health',jsonb_build_object(
      'inventory_sku_count',(select count(*) from public.inventory i where i.branch_id=b.id),
      'low_stock_count',(select count(*) from public.inventory i where i.branch_id=b.id and coalesce(i.alert_enabled,true) and i.quantity<=coalesce(i.min_stock_level,0)),
      'active_online_orders',(select count(*) from public.online_orders o where o.branch_id=b.id and o.status::text in ('pending','confirmed','preparing','ready','shipped')),
      'orders_last_24h',(select count(*) from public.online_orders o where o.branch_id=b.id and o.created_at>=now()-interval '24 hours'),
      'last_order_at',(select max(o.created_at) from public.online_orders o where o.branch_id=b.id),
      'active_delivery_zones',(select count(*) from public.branch_delivery_zones z where z.branch_id=b.id and coalesce(z.is_active,true))
    )
  ) into v_result
  from public.branches b join public.merchants m on m.id=b.merchant_id
  where b.id=p_branch_id;

  return v_result;
end;
$$;

revoke all on function public.get_branch_control_detail_v1(uuid) from public, anon;
grant execute on function public.get_branch_control_detail_v1(uuid) to authenticated, service_role;

create or replace function public.set_branch_channel_v1(
  p_branch_id uuid,
  p_channel text,
  p_enabled boolean,
  p_reason text default null,
  p_message_ar text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_tenant_id uuid;
  v_before jsonb;
  v_after jsonb;
begin
  if p_channel not in ('pos','online_sales','customer_app','marketplace','delivery','pickup') then
    raise exception using errcode='22023',message='INVALID_BRANCH_CHANNEL';
  end if;
  select b.tenant_id into v_tenant_id from public.branches b where b.id=p_branch_id;
  if v_tenant_id is null then raise exception using errcode='P0002',message='BRANCH_NOT_FOUND'; end if;
  if not public.can_manage_business_structure_v1(v_tenant_id) then raise exception using errcode='42501',message='BUSINESS_STRUCTURE_MANAGER_REQUIRED'; end if;
  if not p_enabled and nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception using errcode='22023',message='DISABLE_REASON_REQUIRED'; end if;

  perform pg_advisory_xact_lock(hashtext(p_branch_id::text||':'||p_channel));
  v_before:=private.branch_channel_runtime_v1(p_branch_id,p_channel);

  insert into private.branch_channel_controls_v1(branch_id,channel,configured_enabled,reason,message_ar,source,revision,updated_by,updated_at)
  values(p_branch_id,p_channel,p_enabled,p_reason,p_message_ar,'manual',1,auth.uid(),now())
  on conflict(branch_id,channel) do update set
    configured_enabled=excluded.configured_enabled,
    reason=excluded.reason,
    message_ar=excluded.message_ar,
    source='manual',
    revision=private.branch_channel_controls_v1.revision+1,
    updated_by=auth.uid(),updated_at=now();

  if p_channel='delivery' then
    update public.branches set delivery_enabled=p_enabled,updated_at=now() where id=p_branch_id;
  elsif p_channel='marketplace' and not p_enabled then
    update public.branches set marketplace_customer_enabled=false,updated_at=now() where id=p_branch_id;
  end if;

  v_after:=private.branch_channel_runtime_v1(p_branch_id,p_channel);
  insert into private.business_structure_audit_v1(tenant_id,entity_type,entity_id,branch_id,action,before_state,after_state,reason,actor_user_id)
  values(v_tenant_id,'branch_channel',p_branch_id,p_branch_id,case when p_enabled then 'enable' else 'disable' end,v_before,v_after,p_reason,auth.uid());
  return v_after;
end;
$$;

revoke all on function public.set_branch_channel_v1(uuid,text,boolean,text,text) from public, anon;
grant execute on function public.set_branch_channel_v1(uuid,text,boolean,text,text) to authenticated, service_role;

create or replace function public.create_branch_group_v1(
  p_tenant_id uuid,
  p_code text,
  p_name text,
  p_group_type text default 'custom',
  p_merchant_id uuid default null,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_id uuid;
  v_merchant_tenant uuid;
  v_row jsonb;
begin
  if not public.can_manage_business_structure_v1(p_tenant_id) then raise exception using errcode='42501',message='BUSINESS_STRUCTURE_MANAGER_REQUIRED'; end if;
  if p_group_type not in ('region','operations','franchise_network','marketplace_network','custom') then raise exception using errcode='22023',message='INVALID_BRANCH_GROUP_TYPE'; end if;
  if nullif(btrim(coalesce(p_code,'')),'') is null or nullif(btrim(coalesce(p_name,'')),'') is null then raise exception using errcode='22023',message='GROUP_CODE_AND_NAME_REQUIRED'; end if;
  if p_merchant_id is not null then
    select m.tenant_id into v_merchant_tenant from public.merchants m where m.id=p_merchant_id;
    if v_merchant_tenant is distinct from p_tenant_id then raise exception using errcode='22023',message='GROUP_MERCHANT_TENANT_MISMATCH'; end if;
  end if;

  insert into private.branch_groups_v1(tenant_id,merchant_id,code,name,group_type,metadata,created_by,updated_by)
  values(p_tenant_id,p_merchant_id,lower(btrim(p_code)),btrim(p_name),p_group_type,coalesce(p_metadata,'{}'::jsonb),auth.uid(),auth.uid())
  returning id into v_id;

  select to_jsonb(g) into v_row from private.branch_groups_v1 g where g.id=v_id;
  insert into private.business_structure_audit_v1(tenant_id,entity_type,entity_id,action,after_state,actor_user_id)
  values(p_tenant_id,'branch_group',v_id,'create',v_row,auth.uid());
  return v_row;
end;
$$;

revoke all on function public.create_branch_group_v1(uuid,text,text,text,uuid,jsonb) from public, anon;
grant execute on function public.create_branch_group_v1(uuid,text,text,text,uuid,jsonb) to authenticated, service_role;

create or replace function public.set_branch_group_members_v1(p_group_id uuid,p_branch_ids uuid[])
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_group private.branch_groups_v1%rowtype;
  v_bad integer;
  v_before jsonb;
  v_after jsonb;
begin
  select * into v_group from private.branch_groups_v1 where id=p_group_id for update;
  if v_group.id is null then raise exception using errcode='P0002',message='BRANCH_GROUP_NOT_FOUND'; end if;
  if not public.can_manage_business_structure_v1(v_group.tenant_id) then raise exception using errcode='42501',message='BUSINESS_STRUCTURE_MANAGER_REQUIRED'; end if;

  select count(*) into v_bad
  from unnest(coalesce(p_branch_ids,'{}'::uuid[])) x(branch_id)
  left join public.branches b on b.id=x.branch_id
  where b.id is null or b.tenant_id<>v_group.tenant_id or (v_group.merchant_id is not null and b.merchant_id<>v_group.merchant_id);
  if v_bad>0 then raise exception using errcode='22023',message='BRANCH_GROUP_SCOPE_MISMATCH'; end if;

  select coalesce(jsonb_agg(gm.branch_id order by gm.branch_id),'[]'::jsonb) into v_before
  from private.branch_group_members_v1 gm where gm.group_id=p_group_id;

  delete from private.branch_group_members_v1 where group_id=p_group_id;
  insert into private.branch_group_members_v1(group_id,branch_id,created_by)
  select p_group_id,x.branch_id,auth.uid()
  from (select distinct unnest(coalesce(p_branch_ids,'{}'::uuid[])) as branch_id) x;

  update private.branch_groups_v1 set updated_by=auth.uid(),updated_at=now() where id=p_group_id;
  select coalesce(jsonb_agg(gm.branch_id order by gm.branch_id),'[]'::jsonb) into v_after
  from private.branch_group_members_v1 gm where gm.group_id=p_group_id;

  insert into private.business_structure_audit_v1(tenant_id,entity_type,entity_id,action,before_state,after_state,actor_user_id)
  values(v_group.tenant_id,'branch_group_members',p_group_id,'replace_members',v_before,v_after,auth.uid());
  return jsonb_build_object('group_id',p_group_id,'branch_ids',v_after);
end;
$$;

revoke all on function public.set_branch_group_members_v1(uuid,uuid[]) from public, anon;
grant execute on function public.set_branch_group_members_v1(uuid,uuid[]) to authenticated, service_role;

create or replace function private.guard_online_order_tenant_runtime_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare v_tenant_id uuid;
begin
  if coalesce(new.source_channel,'online') not in ('online','marketplace') then return new; end if;
  v_tenant_id:=new.tenant_id;
  if v_tenant_id is null and new.branch_id is not null then select tenant_id into v_tenant_id from public.branches where id=new.branch_id; end if;
  if v_tenant_id is null and new.merchant_id is not null then select tenant_id into v_tenant_id from public.merchants where id=new.merchant_id; end if;
  if v_tenant_id is not null then
    perform private.assert_tenant_capability_v1(v_tenant_id,'online_sales');
    perform private.assert_tenant_capability_v1(v_tenant_id,'customer_app');
  end if;
  if new.branch_id is not null then
    if coalesce(new.source_channel,'online')='marketplace' then
      if not private.branch_channel_effective_enabled_v1(new.branch_id,'marketplace') then
        raise exception using errcode='55000',message='BRANCH_MARKETPLACE_DISABLED';
      end if;
    else
      if not private.branch_channel_effective_enabled_v1(new.branch_id,'online_sales') then
        raise exception using errcode='55000',message='BRANCH_ONLINE_SALES_DISABLED';
      end if;
      if not private.branch_channel_effective_enabled_v1(new.branch_id,'customer_app') then
        raise exception using errcode='55000',message='BRANCH_CUSTOMER_APP_DISABLED';
      end if;
    end if;
  end if;
  return new;
end;
$$;

revoke all on function private.guard_online_order_tenant_runtime_v1() from public, anon, authenticated;

create or replace function private.guard_saas_pos_sale_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare v_tenant uuid;
begin
  if auth.uid() is not null and public.is_super_admin() then return new; end if;
  if new.branch_id is not null then select tenant_id into v_tenant from public.branches where id=new.branch_id; end if;
  v_tenant:=coalesce(v_tenant,private.resolve_saas_default_tenant_v1());
  if v_tenant is not null then perform private.assert_tenant_capability_v1(v_tenant,'pos'); end if;
  if new.branch_id is not null and not private.branch_channel_effective_enabled_v1(new.branch_id,'pos') then
    raise exception using errcode='55000',message='BRANCH_POS_DISABLED';
  end if;
  return new;
end;
$$;

revoke all on function private.guard_saas_pos_sale_v1() from public, anon, authenticated;

create or replace function public.find_delivery_branch(p_latitude double precision,p_longitude double precision)
returns table(branch_id uuid,branch_name text,distance_km double precision,delivery_radius_km numeric,delivery_fee numeric,min_order_amount numeric,estimated_delivery_minutes integer)
language sql
stable
security definer
set search_path=''
as $$
  with candidates as (
    select b.id,b.name,b.delivery_radius_km,b.delivery_fee,b.min_order_amount,b.estimated_delivery_minutes,
      6371.0*2*asin(sqrt(power(sin(radians((b.latitude-p_latitude)/2)),2)+cos(radians(p_latitude))*cos(radians(b.latitude))*power(sin(radians((b.longitude-p_longitude)/2)),2))) as distance_km
    from public.branches b join public.merchants m on m.id=b.merchant_id
    where b.active=true and b.delivery_enabled=true and m.merchant_type='owned' and m.status='active'
      and b.latitude is not null and b.longitude is not null
      and private.branch_channel_effective_enabled_v1(b.id,'online_sales')
      and private.branch_channel_effective_enabled_v1(b.id,'customer_app')
      and private.branch_channel_effective_enabled_v1(b.id,'delivery')
  )
  select id,name,distance_km,delivery_radius_km,delivery_fee,min_order_amount,estimated_delivery_minutes
  from candidates where distance_km<=delivery_radius_km order by distance_km asc limit 1;
$$;

revoke all on function public.find_delivery_branch(double precision,double precision) from public;
grant execute on function public.find_delivery_branch(double precision,double precision) to anon,authenticated,service_role;
