-- Shared server-side rate limiter for sensitive Edge Functions.
-- The backing table is private and inaccessible to browser roles; only the
-- service role may consume the public SECURITY DEFINER wrapper.

create table if not exists private.edge_rate_limits_v1 (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  key_hash text not null,
  created_at timestamptz not null default now()
);

alter table private.edge_rate_limits_v1 enable row level security;
revoke all on private.edge_rate_limits_v1 from public, anon, authenticated;

create index if not exists edge_rate_limits_v1_lookup_idx
  on private.edge_rate_limits_v1(endpoint, key_hash, created_at desc);

create or replace function public.consume_edge_rate_limit_v1(
  p_endpoint text,
  p_key_hash text,
  p_window_seconds integer,
  p_limit integer
) returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_count integer;
  v_oldest timestamptz;
  v_retry integer:=0;
  v_endpoint text:=left(trim(coalesce(p_endpoint,'')),80);
  v_key text:=left(trim(coalesce(p_key_hash,'')),128);
begin
  if v_endpoint='' or v_key='' or p_window_seconds not between 10 and 86400 or p_limit not between 1 and 1000 then
    raise exception using errcode='22023',message='INVALID_RATE_LIMIT';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_endpoint||':'||v_key,0));

  delete from private.edge_rate_limits_v1
   where endpoint=v_endpoint and key_hash=v_key
     and created_at < now() - interval '1 day';

  select count(*), min(created_at)
    into v_count, v_oldest
  from private.edge_rate_limits_v1
  where endpoint=v_endpoint and key_hash=v_key
    and created_at >= now() - make_interval(secs => p_window_seconds);

  if v_count >= p_limit then
    v_retry:=greatest(
      1,
      ceil(extract(epoch from ((v_oldest + make_interval(secs => p_window_seconds)) - now())))::integer
    );
    return jsonb_build_object(
      'allowed',false,
      'remaining',0,
      'retry_after_seconds',v_retry
    );
  end if;

  insert into private.edge_rate_limits_v1(endpoint,key_hash)
  values(v_endpoint,v_key);

  return jsonb_build_object(
    'allowed',true,
    'remaining',greatest(0,p_limit-v_count-1),
    'retry_after_seconds',0
  );
end;
$$;

revoke all on function public.consume_edge_rate_limit_v1(text,text,integer,integer)
  from public, anon, authenticated;
grant execute on function public.consume_edge_rate_limit_v1(text,text,integer,integer)
  to service_role;
