alter table private.hr_payroll_runs
  add column if not exists payment_responsible_user_id uuid references public.users(id) on delete restrict,
  add column if not exists payment_requested_by uuid references public.users(id) on delete restrict,
  add column if not exists payment_requested_at timestamptz,
  add column if not exists payment_delegated_task_id uuid references public.operations_tasks(id) on delete restrict;
create index if not exists hr_payroll_runs_payment_responsible_idx on private.hr_payroll_runs(payment_responsible_user_id) where payment_responsible_user_id is not null;
create index if not exists hr_payroll_runs_payment_requested_by_idx on private.hr_payroll_runs(payment_requested_by) where payment_requested_by is not null;
create index if not exists hr_payroll_runs_payment_delegated_task_idx on private.hr_payroll_runs(payment_delegated_task_id) where payment_delegated_task_id is not null;

alter table private.hr_payroll_runs drop constraint if exists hr_payroll_runs_payment_source_check;
alter table private.hr_payroll_runs add constraint hr_payroll_runs_payment_source_check check (
  (payment_source_kind is null and payment_cash_account_id is null and payment_payment_account_id is null and payment_cash_ledger_id is null and payment_payment_ledger_id is null)
  or (payment_source_kind in ('branch_safe','pos_drawer') and payment_cash_account_id is not null and payment_payment_account_id is null and payment_payment_ledger_id is null)
  or (payment_source_kind='bank' and payment_cash_account_id is null and payment_payment_account_id is not null and payment_cash_ledger_id is null)
);

create or replace function public.get_hr_payroll_treasury_queue_v1(p_branch_id uuid,p_limit integer default 24)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare v_items jsonb;v_limit integer:=least(greatest(coalesce(p_limit,24),1),60);
begin
 if auth.uid() is null then raise exception using errcode='42501',message='AUTH_REQUIRED';end if;
 if not (private.staff_is_super_admin(auth.uid()) or public.staff_has_permission('finance.manage',p_branch_id)) then raise exception using errcode='42501',message='FINANCE_MANAGE_DENIED';end if;
 select coalesce(jsonb_agg(jsonb_build_object('run_id',r.id,'month',r.month,'year',r.year,'status',r.status,'total_net',r.total_net,'locked_at',r.locked_at,'payment_source_kind',r.payment_source_kind,'payment_source_account_id',coalesce(r.payment_cash_account_id,r.payment_payment_account_id),'payment_source_name',r.payment_account_name_snapshot,'responsible_user_id',r.payment_responsible_user_id,'responsible_user_name',u.name,'delegated_task_id',r.payment_delegated_task_id,'delegated_task_status',t.status,'payment_reference',r.payment_reference) order by r.year desc,r.month desc),'[]') into v_items
 from (select * from private.hr_payroll_runs where branch_id=p_branch_id and status='locked' order by year desc,month desc limit v_limit) r left join public.users u on u.id=r.payment_responsible_user_id left join public.operations_tasks t on t.id=r.payment_delegated_task_id;
 return jsonb_build_object('version',1,'branch_id',p_branch_id,'items',v_items,'generated_at',now());
end;$$;

create or replace function public.delegate_hr_payroll_payment_v4(p_run_id uuid,p_source_kind text,p_source_account_id uuid,p_note text,p_reference text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_run private.hr_payroll_runs%rowtype;v_res jsonb;v_resp uuid;v_resp_name text;v_account_name text;v_balance numeric;v_task public.operations_tasks%rowtype;
begin
 if auth.uid() is null then raise exception using errcode='42501',message='AUTH_REQUIRED';end if;
 if p_source_kind not in ('branch_safe','pos_drawer','bank') or p_source_account_id is null then raise exception using errcode='22023',message='PAYROLL_PAYMENT_SOURCE_REQUIRED';end if;
 if length(trim(coalesce(p_note,'')))<3 then raise exception using errcode='22023',message='PAYROLL_PAYMENT_NOTE_REQUIRED';end if;
 if length(trim(coalesce(p_reference,'')))<2 then raise exception using errcode='22023',message='PAYROLL_PAYMENT_REFERENCE_REQUIRED';end if;
 select * into v_run from private.hr_payroll_runs where id=p_run_id for update;if v_run.id is null then raise exception using errcode='22023',message='PAYROLL_RUN_NOT_FOUND';end if;
 if not (private.staff_is_super_admin(auth.uid()) or public.staff_has_permission('finance.manage',v_run.branch_id)) then raise exception using errcode='42501',message='PAYROLL_PAYMENT_DENIED';end if;
 if v_run.status<>'locked' then raise exception using errcode='55000',message='PAYROLL_NOT_LOCKED';end if;
 v_res:=private.resolve_finance_account_custodian_v1(v_run.branch_id,p_source_kind,p_source_account_id);if v_res is null then raise exception using errcode='22023',message='PAYROLL_PAYMENT_SOURCE_UNAVAILABLE';end if;
 v_resp:=nullif(v_res->>'responsible_user_id','')::uuid;v_resp_name:=v_res->>'responsible_user_name';v_account_name:=v_res->>'account_name';v_balance:=coalesce((v_res->>'balance')::numeric,0);
 if v_resp is null then raise exception using errcode='55000',message='PAYROLL_PAYMENT_SOURCE_HAS_NO_RESPONSIBLE';end if;
 if round(v_run.total_net,2)>round(v_balance,2) then raise exception using errcode='22023',message='PAYROLL_INSUFFICIENT_BALANCE';end if;
 if v_run.payment_delegated_task_id is not null then select * into v_task from public.operations_tasks where id=v_run.payment_delegated_task_id;end if;
 if v_task.id is not null and v_task.status in ('claimed','in_progress') then
  if v_run.payment_source_kind=p_source_kind and coalesce(v_run.payment_cash_account_id,v_run.payment_payment_account_id)=p_source_account_id and v_run.payment_responsible_user_id=v_resp then return jsonb_build_object('ok',true,'idempotent',true,'delegated_task_id',v_task.id,'responsible_user_id',v_resp,'responsible_user_name',v_resp_name,'source_account_name',v_account_name);end if;
  raise exception using errcode='55000',message='PAYROLL_ALREADY_DELEGATED';
 end if;
 insert into public.operations_tasks(branch_id,task_type,source_kind,source_id,amount,priority,status,title,description,claimed_by,claimed_at,metadata,created_by)
 values(v_run.branch_id,'treasury_disbursement','hr_treasury_payroll',v_run.id,0,'high','claimed','صرف مسير رواتب معتمد','راجع صرف رواتب '||v_run.month::text||'/'||v_run.year::text||' من '||v_account_name||' ثم أكد بعد التسليم/التحويل.',v_resp,now(),jsonb_build_object('run_id',v_run.id,'month',v_run.month,'year',v_run.year,'total_net',v_run.total_net,'source_kind',p_source_kind,'source_account_id',p_source_account_id,'source_account_name',v_account_name,'responsible_user_id',v_resp,'reference',trim(p_reference),'sensitive',true),auth.uid()) returning * into v_task;
 update private.hr_payroll_runs set payment_source_kind=p_source_kind,payment_cash_account_id=case when p_source_kind in ('branch_safe','pos_drawer') then p_source_account_id else null end,payment_payment_account_id=case when p_source_kind='bank' then p_source_account_id else null end,payment_account_name_snapshot=v_account_name,payment_responsible_user_id=v_resp,payment_requested_by=auth.uid(),payment_requested_at=now(),payment_delegated_task_id=v_task.id,payment_reference=trim(p_reference),payment_cash_ledger_id=null,payment_payment_ledger_id=null,updated_at=now() where id=v_run.id;
 insert into private.hr_audit_log(entity_type,entity_id,action,actor_user_id,branch_id,after_data) values('payroll_run',v_run.id,'payment_delegated',auth.uid(),v_run.branch_id,jsonb_build_object('source_kind',p_source_kind,'source_account_id',p_source_account_id,'source_name',v_account_name,'responsible_user_id',v_resp,'responsible_user_name',v_resp_name,'treasury_task_id',v_task.id,'reference',trim(p_reference),'note',trim(p_note)));
 return jsonb_build_object('ok',true,'idempotent',false,'delegated_task_id',v_task.id,'responsible_user_id',v_resp,'responsible_user_name',v_resp_name,'source_account_name',v_account_name,'balance',v_balance,'amount',v_run.total_net,'month',v_run.month,'year',v_run.year);
end;$$;

create or replace function public.get_my_hr_treasury_payroll_task_v1(p_task_id uuid)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare v_task public.operations_tasks%rowtype;v_run private.hr_payroll_runs%rowtype;
begin
 if auth.uid() is null then raise exception using errcode='42501',message='AUTH_REQUIRED';end if;
 select * into v_task from public.operations_tasks where id=p_task_id and source_kind='hr_treasury_payroll';if v_task.id is null then raise exception using errcode='22023',message='TREASURY_TASK_NOT_FOUND';end if;
 if v_task.claimed_by is distinct from auth.uid() and not (private.staff_is_super_admin(auth.uid()) or public.staff_has_permission('finance.manage',v_task.branch_id)) then raise exception using errcode='42501',message='TREASURY_TASK_ACCESS_DENIED';end if;
 select * into v_run from private.hr_payroll_runs where id=v_task.source_id;if v_run.id is null then raise exception using errcode='22023',message='PAYROLL_RUN_NOT_FOUND';end if;
 return jsonb_build_object('task',jsonb_build_object('id',v_task.id,'status',v_task.status,'claimed_by',v_task.claimed_by,'created_at',v_task.created_at),'payroll',jsonb_build_object('id',v_run.id,'month',v_run.month,'year',v_run.year,'total_net',v_run.total_net,'status',v_run.status),'source',jsonb_build_object('kind',v_run.payment_source_kind,'account_id',coalesce(v_run.payment_cash_account_id,v_run.payment_payment_account_id),'account_name',v_run.payment_account_name_snapshot,'responsible_user_id',v_run.payment_responsible_user_id,'balance',case when v_run.payment_source_kind in ('branch_safe','pos_drawer') then private.cash_account_balance(v_run.payment_cash_account_id) else private.payment_account_balance(v_run.payment_payment_account_id) end),'reference',v_run.payment_reference);
end;$$;

create or replace function public.confirm_hr_treasury_payroll_v1(p_task_id uuid,p_note text,p_reference text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_task public.operations_tasks%rowtype;v_run private.hr_payroll_runs%rowtype;v_cash public.cash_accounts%rowtype;v_bank public.payment_accounts%rowtype;v_balance numeric;v_ledger uuid;v_ref text;i record;a record;v_remaining numeric;v_take numeric;
begin
 if auth.uid() is null then raise exception using errcode='42501',message='AUTH_REQUIRED';end if;if length(trim(coalesce(p_note,'')))<3 then raise exception using errcode='22023',message='TREASURY_CONFIRM_NOTE_REQUIRED';end if;
 select * into v_task from public.operations_tasks where id=p_task_id for update;if v_task.id is null or v_task.source_kind<>'hr_treasury_payroll' then raise exception using errcode='22023',message='TREASURY_TASK_NOT_FOUND';end if;if v_task.status='completed' then return jsonb_build_object('ok',true,'idempotent',true,'task_id',v_task.id);end if;if v_task.claimed_by is distinct from auth.uid() then raise exception using errcode='42501',message='TREASURY_TASK_NOT_OWNER';end if;if v_task.status not in ('claimed','in_progress') then raise exception using errcode='55000',message='TREASURY_TASK_NOT_CONFIRMABLE';end if;
 select * into v_run from private.hr_payroll_runs where id=v_task.source_id for update;if v_run.id is null then raise exception using errcode='22023',message='PAYROLL_RUN_NOT_FOUND';end if;if v_run.status<>'locked' or v_run.payment_delegated_task_id is distinct from v_task.id or v_run.payment_responsible_user_id is distinct from auth.uid() then raise exception using errcode='42501',message='TREASURY_RESPONSIBILITY_CHANGED';end if;v_ref:=coalesce(nullif(trim(coalesce(p_reference,'')),''),v_run.payment_reference);if length(trim(coalesce(v_ref,'')))<2 then raise exception using errcode='22023',message='PAYROLL_PAYMENT_REFERENCE_REQUIRED';end if;
 if v_run.payment_source_kind in ('branch_safe','pos_drawer') then select * into v_cash from public.cash_accounts where id=v_run.payment_cash_account_id and branch_id=v_run.branch_id and account_type=v_run.payment_source_kind and active;if v_cash.id is null then raise exception using errcode='22023',message='TREASURY_SOURCE_UNAVAILABLE';end if;if v_run.payment_source_kind='branch_safe' and v_cash.custodian_user_id is distinct from auth.uid() then raise exception using errcode='42501',message='TREASURY_RESPONSIBILITY_CHANGED';end if;if v_run.payment_source_kind='pos_drawer' and not exists(select 1 from public.pos_shifts s where s.drawer_account_id=v_cash.id and s.status='open' and s.user_id=auth.uid()) then raise exception using errcode='42501',message='TREASURY_DRAWER_SHIFT_CHANGED';end if;perform pg_advisory_xact_lock(hashtextextended('cash-account:'||v_cash.id::text,111));v_balance:=private.cash_account_balance(v_cash.id);if round(v_run.total_net,2)>round(v_balance,2) then raise exception using errcode='22023',message='TREASURY_INSUFFICIENT_BALANCE';end if;if round(v_run.total_net,2)>0 then insert into public.cash_ledger(account_id,branch_id,entry_type,signed_amount,reference_type,reference_id,description,metadata,created_by) values(v_cash.id,v_run.branch_id,'hr_payroll_payout',-round(v_run.total_net,2),'hr_payroll_run',v_run.id,'صرف رواتب '||v_run.month::text||'/'||v_run.year::text,jsonb_build_object('treasury_task_id',v_task.id,'responsible_user_id',auth.uid(),'payment_reference',v_ref),auth.uid()) returning id into v_ledger;end if;
 else select * into v_bank from public.payment_accounts where id=v_run.payment_payment_account_id and branch_id=v_run.branch_id and account_type='bank' and active;if v_bank.id is null then raise exception using errcode='22023',message='TREASURY_SOURCE_UNAVAILABLE';end if;if v_bank.custodian_user_id is distinct from auth.uid() then raise exception using errcode='42501',message='TREASURY_RESPONSIBILITY_CHANGED';end if;perform pg_advisory_xact_lock(hashtextextended('payment-account:'||v_bank.id::text,112));v_balance:=private.payment_account_balance(v_bank.id);if round(v_run.total_net,2)>round(v_balance,2) then raise exception using errcode='22023',message='TREASURY_INSUFFICIENT_BALANCE';end if;if round(v_run.total_net,2)>0 then insert into public.payment_ledger(account_id,branch_id,entry_type,signed_amount,payment_method,external_reference,description,metadata,created_by) values(v_bank.id,v_run.branch_id,'hr_payroll_payout',-round(v_run.total_net,2),'bank',v_ref,'صرف رواتب '||v_run.month::text||'/'||v_run.year::text,jsonb_build_object('run_id',v_run.id,'treasury_task_id',v_task.id,'responsible_user_id',auth.uid()),auth.uid()) returning id into v_ledger;end if;end if;
 for i in select * from private.hr_payroll_items where run_id=v_run.id order by employee_name_snapshot loop update public.salaries set amount=i.net_amount,status='paid',payment_date=current_date,notes='Payroll V2 run:'||v_run.id::text||' | Ref:'||v_ref,updated_at=now() where employee_id=i.employee_id and month=v_run.month and year=v_run.year and notes like 'Payroll V2 run:%';v_remaining:=i.advance_deduction;if v_remaining>0 then for a in select * from private.hr_salary_advances where employee_id=i.employee_id and branch_id=v_run.branch_id and status='active' and outstanding_amount>0 order by paid_at nulls last,created_at for update loop exit when v_remaining<=0;v_take:=least(v_remaining,a.monthly_deduction,a.outstanding_amount);if v_take>0 then insert into private.hr_salary_advance_repayments(advance_id,payroll_item_id,amount,created_by) values(a.id,i.id,v_take,auth.uid()) on conflict(advance_id,payroll_item_id) do nothing;update private.hr_salary_advances set outstanding_amount=greatest(outstanding_amount-v_take,0),status=case when outstanding_amount-v_take<=0 then 'settled' else 'active' end,settled_at=case when outstanding_amount-v_take<=0 then now() else settled_at end,updated_at=now() where id=a.id;v_remaining:=v_remaining-v_take;end if;end loop;end if;end loop;
 update private.hr_payroll_runs set status='paid',paid_by=auth.uid(),paid_at=now(),payment_reference=v_ref,payment_cash_ledger_id=case when payment_source_kind in ('branch_safe','pos_drawer') then v_ledger else null end,payment_payment_ledger_id=case when payment_source_kind='bank' then v_ledger else null end,updated_at=now() where id=v_run.id returning * into v_run;
 update public.operations_tasks set status='completed',started_at=coalesce(started_at,now()),completed_by=auth.uid(),completed_at=now(),failure_reason=null,metadata=coalesce(metadata,'{}')||jsonb_build_object('resolution_note',trim(p_note),'ledger_entry_id',v_ledger,'confirmed_at',now()),updated_at=now() where id=v_task.id;insert into public.operations_task_events(task_id,event_type,actor_id,note,metadata) values(v_task.id,'completed',auth.uid(),trim(p_note),jsonb_build_object('ledger_entry_id',v_ledger,'payment_reference',v_ref));insert into private.hr_audit_log(entity_type,entity_id,action,actor_user_id,branch_id,after_data) values('payroll_run',v_run.id,'paid',auth.uid(),v_run.branch_id,to_jsonb(v_run));
 return jsonb_build_object('ok',true,'idempotent',false,'run',to_jsonb(v_run),'amount',v_run.total_net,'source_kind',v_run.payment_source_kind,'source_account_id',coalesce(v_run.payment_cash_account_id,v_run.payment_payment_account_id),'source_account_name',v_run.payment_account_name_snapshot,'source_balance_after',case when v_run.payment_source_kind in ('branch_safe','pos_drawer') then private.cash_account_balance(v_run.payment_cash_account_id) else private.payment_account_balance(v_run.payment_payment_account_id) end);
end;$$;

create or replace function public.reject_hr_treasury_payroll_v1(p_task_id uuid,p_reason text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_task public.operations_tasks%rowtype;v_run private.hr_payroll_runs%rowtype;
begin if auth.uid() is null then raise exception using errcode='42501',message='AUTH_REQUIRED';end if;if length(trim(coalesce(p_reason,'')))<3 then raise exception using errcode='22023',message='TREASURY_REJECTION_REASON_REQUIRED';end if;select * into v_task from public.operations_tasks where id=p_task_id for update;if v_task.id is null or v_task.source_kind<>'hr_treasury_payroll' then raise exception using errcode='22023',message='TREASURY_TASK_NOT_FOUND';end if;if v_task.claimed_by is distinct from auth.uid() then raise exception using errcode='42501',message='TREASURY_TASK_NOT_OWNER';end if;select * into v_run from private.hr_payroll_runs where id=v_task.source_id for update;if v_run.id is null then raise exception using errcode='22023',message='PAYROLL_RUN_NOT_FOUND';end if;update public.operations_tasks set status='cancelled',completed_by=auth.uid(),completed_at=now(),failure_reason=trim(p_reason),updated_at=now() where id=v_task.id;insert into public.operations_task_events(task_id,event_type,actor_id,note) values(v_task.id,'rejected',auth.uid(),trim(p_reason));update private.hr_payroll_runs set payment_source_kind=null,payment_cash_account_id=null,payment_payment_account_id=null,payment_account_name_snapshot=null,payment_responsible_user_id=null,payment_requested_by=null,payment_requested_at=null,payment_delegated_task_id=null,payment_cash_ledger_id=null,payment_payment_ledger_id=null,updated_at=now() where id=v_run.id;insert into private.hr_audit_log(entity_type,entity_id,action,actor_user_id,branch_id,after_data) values('payroll_run',v_run.id,'payment_rejected_by_custodian',auth.uid(),v_run.branch_id,jsonb_build_object('reason',trim(p_reason),'treasury_task_id',v_task.id));return jsonb_build_object('ok',true,'run_id',v_run.id,'status','locked');end;$$;

create or replace function public.mark_hr_payroll_paid_v3(p_run_id uuid,p_source_kind text,p_source_account_id uuid,p_payment_reference text)
returns jsonb language plpgsql security definer set search_path='' as $$begin if auth.uid() is null then raise exception using errcode='42501',message='AUTH_REQUIRED';end if;raise exception using errcode='55000',message='PAYROLL_DELEGATION_REQUIRED';end;$$;
create or replace function public.mark_hr_payroll_paid_v2(p_run_id uuid,p_payment_reference text)
returns jsonb language plpgsql security definer set search_path='' as $$begin if auth.uid() is null then raise exception using errcode='42501',message='AUTH_REQUIRED';end if;raise exception using errcode='55000',message='PAYROLL_DELEGATION_REQUIRED';end;$$;

create or replace function private.operations_task_can_claim(p_source_kind text,p_branch_id uuid)
returns boolean language sql stable security definer set search_path='' as $$select case when p_source_kind='pos_refund' then public.staff_has_permission('sales.refund',p_branch_id) or public.staff_has_permission('finance.manage',p_branch_id) when p_source_kind='online_refund' then public.staff_has_permission('online_money.settle_digital',p_branch_id) when p_source_kind='shift_reconciliation' then public.staff_has_permission('pos.manage_shifts',p_branch_id) or public.staff_has_permission('finance.manage',p_branch_id) when p_source_kind='cash_handoff' then public.staff_has_permission('finance.manage',p_branch_id) or public.staff_has_permission('pos.manage_shifts',p_branch_id) when p_source_kind='inventory_count' then public.staff_has_permission('inventory.count',p_branch_id) when p_source_kind='inventory_recount' then public.staff_has_permission('inventory.recount',p_branch_id) when p_source_kind='inventory_adjustment' then public.staff_has_permission('inventory.approve_adjustment',p_branch_id) when p_source_kind in ('inventory_transfer_dispatch','inventory_transfer_receive') then public.staff_has_permission('inventory.transfer',p_branch_id) when p_source_kind='inventory_transfer_variance' then public.staff_has_permission('inventory.manage',p_branch_id) or public.staff_has_permission('inventory.approve_adjustment',p_branch_id) when p_source_kind='attendance_exception' then public.staff_has_permission('hr.attendance.approve',p_branch_id) or public.staff_has_permission('branch.manage_staff',p_branch_id) when p_source_kind='hr_request' then private.hr_request_can_review_for_user_v1(auth.uid(),p_branch_id) when p_source_kind='hr_salary_advance_payout' then public.staff_has_permission('finance.manage',p_branch_id) when p_source_kind in ('hr_treasury_payout','hr_treasury_payroll') then public.has_branch_access(auth.uid(),p_branch_id) when p_source_kind='hr_attendance_correction_apply' then public.staff_has_permission('hr.attendance.manage',p_branch_id) or public.staff_has_permission('branch.manage_staff',p_branch_id) else false end;$$;

create or replace function public.release_operations_task(p_task_id uuid,p_note text default null)
returns jsonb language plpgsql security definer set search_path='' as $$declare v_task public.operations_tasks%rowtype;begin if auth.uid() is null then raise exception using errcode='42501',message='AUTH_REQUIRED';end if;select * into v_task from public.operations_tasks where id=p_task_id for update;if v_task.id is null then raise exception using errcode='22023',message='TASK_NOT_FOUND';end if;if v_task.source_kind in ('hr_treasury_payout','hr_treasury_payroll') then raise exception using errcode='55000',message='TASK_REQUIRES_SPECIAL_COMPLETION';end if;if v_task.status not in ('claimed','in_progress','failed') then raise exception using errcode='55000',message='TASK_NOT_RELEASABLE';end if;if v_task.claimed_by is distinct from auth.uid() and not public.staff_has_permission('finance.manage',v_task.branch_id) and not (v_task.source_kind='shift_reconciliation' and public.staff_has_permission('pos.manage_shifts',v_task.branch_id)) then raise exception using errcode='42501',message='TASK_RELEASE_DENIED';end if;update public.operations_tasks set status='open',claimed_by=null,claimed_at=null,started_at=null,failure_reason=null,updated_at=now() where id=v_task.id returning * into v_task;insert into public.operations_task_events(task_id,event_type,actor_id,note) values(v_task.id,'released',auth.uid(),nullif(trim(coalesce(p_note,'')),''));return to_jsonb(v_task);end$$;

do $$declare v_def text;begin select pg_get_functiondef(p.oid) into v_def from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='list_operations_tasks' and pg_get_function_identity_arguments(p.oid)='p_branch_id uuid, p_scope text, p_limit integer';if position('(''hr_request'',''hr_salary_advance_payout'',''hr_treasury_payout'')' in v_def)>0 then v_def:=replace(v_def,'(''hr_request'',''hr_salary_advance_payout'',''hr_treasury_payout'')','(''hr_request'',''hr_salary_advance_payout'',''hr_treasury_payout'',''hr_treasury_payroll'')');execute v_def;end if;end$$;

revoke all on function public.get_hr_payroll_treasury_queue_v1(uuid,integer) from public,anon;
revoke all on function public.delegate_hr_payroll_payment_v4(uuid,text,uuid,text,text) from public,anon;
revoke all on function public.get_my_hr_treasury_payroll_task_v1(uuid) from public,anon;
revoke all on function public.confirm_hr_treasury_payroll_v1(uuid,text,text) from public,anon;
revoke all on function public.reject_hr_treasury_payroll_v1(uuid,text) from public,anon;
grant execute on function public.get_hr_payroll_treasury_queue_v1(uuid,integer) to authenticated;
grant execute on function public.delegate_hr_payroll_payment_v4(uuid,text,uuid,text,text) to authenticated;
grant execute on function public.get_my_hr_treasury_payroll_task_v1(uuid) to authenticated;
grant execute on function public.confirm_hr_treasury_payroll_v1(uuid,text,text) to authenticated;
grant execute on function public.reject_hr_treasury_payroll_v1(uuid,text) to authenticated;
